#import "template/template.typ": thesis, tlt, indent, acknowledgement, appendix

// Magic code for fake bold
// reference: https://github.com/typst/typst/issues/394#issuecomment-1987055478
#show text.where(weight: "bold").or(strong): it => {
  show regex("\p{script=Han}"): set text(stroke: 0.025em)
  it
}

#let (
  doc, cover, front-matter, abstract-zh, abstract-en, outline-page, main-matter
) = thesis(
  title: [就“基于分布式光纤的非常规油气藏微震观测与分析”的报告],

  author: "*******",
  student-id: "*************",
  major: "地球物理学",
  school: "****",
  supervisor: "---",

  date: "二 〇 二 四 年 六 月",
)


#show: doc

#cover()

// #declaration(
//   author_signature_path: "/assets/whu.png",
//   mentor_signature_path: "/assets/whu.png"
// )

#show: front-matter

#show "typst": typst => underline(link("https://typst.app")[#typst]) // mk `typst` a link
#show "latex": latex => box(baseline:22.5%)[#image("assets/LaTeX_logo.svg", height: 13pt)] // mk `latex` svg

#abstract-zh(
  keywords: ("弘毅研讨课", "作业")
)[
  本文是-----------------。文中就线上学术报告“基于分布式光纤的非常规油气藏微震观测与分析”进行了总结和讨论。在本文写作的同时还对新型排版工具typst进行了测试（所以本文件也是由 typst 生成）。
]

// #pagebreak()
#v(100pt)

#abstract-en(
  keywords: ("Hongyi Seminar", "Homework")
)[
This paper is a ---------------------------------. The paper summarizes and discusses the online academic report “Distributed Fiber Optic-based Microseismic Observation and Analysis of Unconventional Reservoirs”. The author test new layout tool typst while writing this paper (so this paper is also generated by typst).
]


#pagebreak()

#outline-page()

#pagebreak()

#show: main-matter

= 线上报告本体

报告以基于分布式光纤的非常规油气藏微震观测与分析为主题，报告者为来自南方科技大学的罗彬。这份报告可以在#underline(link("https://www.bilibili.com/video/BV1jG411M7Jt/")[这里])观看。

== DAS和背景介绍

报告首先介绍了分布式光纤传感（DAS）的基本原理和特性。光纤地震仪和传统的三分量地震仪不同，光纤地震仪只对沿光纤方向的应变敏感。所以P波和S波的入射方向和沿光纤方向之间的夹角的变化会导致DAS的响应也有所不同。由P波和S波以及光纤对于应变的响应关系，可以推导出：
$ "P_wave" ~ cos^2 theta $ $ "S_wave" ~ sin 2 theta $
此外，光纤地震仪不是严格的单点采样。由于其标距效应，其相当于对目标信号在空间上进行了一个滑动平均（和一个方波进行了卷积），所以DAS对于波长小于标距的信号具有明显的方向性相应，而对于远长于标距的信号的方向性响应则较弱。

本报告作者的研究是“非常规油气藏”。所谓的“非常规油气藏”即指页岩油和页岩气，其在开采过程中使用水力压裂技术。压裂技术是通过在井眼中注入高压液体，使岩石发生裂缝，从而增加岩石的渗透率。压裂过程中导致的岩层破裂会产生微震。这些微震信号可以被同井或是专用井中的光纤记录下来。井下光纤覆铠，耐磨损性能好所以可以在作业期间持续进行井下观测。作者主要的研究就以此为背景开展。

== DAS在水力压裂中的应用

DAS在水力压裂中的应用主要是检测压裂的破裂场。这方面有三种手段，一类是观测压裂前后的地震信号作对比，计算破裂，如@fig:base-line 所示。另一类是在压裂过程中持续观测应变场，如@fig:wwing 所示。第三类是观测微震信号并对其作分析。本报告中主要聚焦于第三个方法。

#figure(image("./assets/baseline.png"), caption: [水压裂前后观测人工源地震的对比显示出新的破裂@byerley2018time]) <base-line>

#figure(image("./assets/wwimg.png"), caption: [水压裂作业中的持续观测能发现岩层中应力的持续变化@jin2017hydraulic]) <wwing>

作者使用是数据来自德州的Eagle Ford岩层。此岩层的特点是上下两个高速层夹着中间的低速页岩层。这就会产生全反射和导波，如@fig:microseimdas 所示。

#figure(image("./assets/microseimdas.png"), caption: [光纤对于压裂微震的响应，注意到导波的产生]) <microseimdas>

由于只有震源在低速层内才会产生导波，所以可以通过导波的存在来判断震源的位置。这方面可以通过人工生成的加噪声图像训练CNN来识别。同时，注意到有些导波有奇阶和第一高阶的特质，而有些没有这些mode，这可以用来判断震源在低速层中的位置。

为了获得震源位置和光纤之间的距离，需要一个已知源。在压裂场景中可以使用钻头的信号来校准。井下噪声很少，不能通过互相关来做。

通过微震位置的集合，可以发现其分布具有一定规律。在本例中，其分布呈现一定的倾斜状，可能是由于压裂没有按照最小应力的方向进行。

在多数的较大震级（大于-1级）的事件中，都可以发现如@fig:near-field 所示的近场信号。从Aki and Richards的公式出发模拟，可以得到和观测相同的结果。由历史研究可知，从这些近场结果中，如果介质各向同性，那么我们不能得到更多的信息@vera2020strain。但是在实际工程中，我们有可能可以更好地约束震源参数，这需要进一步研究。

#figure(image("./assets/nf.png"), caption: [可以观测到近场的出现，P-S有大幅度的反相加强@luo2021near]) <near-field>

= 讨论

光纤在井下观测中具有明显的优势。得益于光纤（及其覆铠）的机械强度，DAS可以在地下持续观测。而且光纤相较传统地震仪在观测时更接近震源，测点更密集，这为未来的大规模密集观测成像，乃至于地下云图的实现提供了可能性。在页岩油气藏的开采中，光纤传感可以更灵敏地感知微震，从而对压裂作业的效果进行实时监测，进而指导作业。

但是光纤同样尤其弱点，那就是它是单分量的。这导致本报告中的例子只靠光纤不能准确定震源点（最佳情况也只能限制到左右对称的两个点上），需要多方面的额外信息来确定。

根据报道，在德州Eagle ford地区就有上万口已经打下去的井@wells2022。而已经安装了DAS的则是少数，多数的井都是过去打的，其中没有预埋光纤。如果能够利用那些已经存在的井，或许有可能能以更低的成本实现大规模的密集观测。

#pagebreak()

#bibliography(("./bib/bib.bib"), style: "gb-7714-2005-numeric")

// #acknowledgement()[

// ]

#appendix()[

typst本次测试中表现良好，在#underline(link("https://github.com/Enter-tainer/typst-preview")[typst-preview])项目的帮助下，可以实时预览修改的效果，不需要像latex一样等待编译。typst在语法上相较latex也更加简洁明快，缺点是可定制性暂时还不如latex，各种排版细节还需要进一步完善。但是对于一般项目已经达到了可用水平，且体感强于latex。

本文的源码可以在#underline(link("https://github.com/Daillusorisch/HYSeminarAssignment")[这个github仓库])上查看。

]
